[package]
name = "stijn/baby-vs-granny"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
    Comm = "sleitnick/comm@0.3.1"
    Component = "sleitnick/component@2.4.6"
    EnumList = "sleitnick/enum-list@2.0.1"
    Input = "sleitnick/input@2.1.1"
    Knit = "sleitnick/knit@^1.5"
    Option = "sleitnick/option@1.0.4"
    Promise = "evaera/promise@4.0.0"
    Signal = "sleitnick/signal@1.2.0"
    Streamable = "sleitnick/streamable@1.2.3"
    TableUtil = "sleitnick/table-util@1.2.0"
    Timer = "sleitnick/timer@1.1.2"
    Trove = "sleitnick/trove@0.5.0"
    universe = "justethecoder/universe@0.0.1"
    roact = "firere/roact@1.5.0"
    red = "uncontained0/red@1.2.2"
    remote = "sleitnick/remote@1.0.4"
    profileservice = "nidoxs/profileservice@1.0.0"
    easyviewmodel = "xswezan/easyviewmodel@0.1.6"
    viewportfitter = "legendoj1/viewportfitter@1.0.1"